parameters:
  - name: jobName
    default: ''
  - name: poolName
    default: 'Salvador Local'

jobs:
  - job: ${{ parameters.jobName }}
    pool: ${{ parameters.poolName }}
    steps:
      - script: echo ${{ parameters.jobName }}
      - script: echo ${{ parameters.poolName }}
