# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

variables:
  buildConfiguration: 'Release'

jobs:
  - template: params.template.yml
    parameters:
      jobName: 'job_01'
      poolName: 'Salvador Local'
  
  - template: params.template.yml
    parameters:
      jobName: 'job_2'
      poolName: 'Salvador Local'
