# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

stages:
- stage: 'Stage_01'
  displayName: 'Stage 01'
  pool: 'Salvador Local'
  jobs:
  - job: 
    displayName: 'State 01 Job 01'
    steps:
    - script: echo 'State 01 Job 01'
  - job:
    displayName: 'State 01 Job 02'
    steps:
    - script: echo 'State 01 Job 02'
- stage: 'Stage_02'
  displayName: 'Stage 02'
  pool: 'Salvador Local'
  jobs:
  - job: 
    displayName: 'State 02 Job 01'
    steps:
    - script: echo 'State 02 Job 01'
  - job:
    displayName: 'State 02 Job 02'
    steps:
    - script: echo 'State 02 Job 02'
